# Expiration service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-expiration
  template:
    metadata:
      labels:
        app: ticketing-expiration
    spec:
      containers:
        - name: ticketing-expiration
          image: pashkoostap/ticketing-expiration
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 125Mi
          env:
            - name: REDIS_HOST
              value: ticketing-expiration-redis-srv
            - name: NATS_URL
              value: 'http://ticketing-nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing-nats'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
# Redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-expiration-redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-expiration-redis
  template:
    metadata:
      labels:
        app: ticketing-expiration-redis
    spec:
      containers:
        - name: ticketing-expiration-redis
          image: redis
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 125Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-expiration-redis-srv
spec:
  selector:
    app: ticketing-expiration-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
