name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: cd client && docker build -f ./Dockerfile -t pashkoostap/ticketing-client .
      - run: docker push pashkoostap/ticketing-client
      - run: cd client && docker build -f ./Dockerfile.prod -t pashkoostap/ticketing-client-prod .
      - run: docker push pashkoostap/ticketing-client-prod
